#!/usr/bin/env python3
import os
import sys

# Variables
microscripts = sys.path[0]
shell = os.environ["SHELL"]
home = os.environ["HOME"]

# ZSH or BASH?
if ("zsh" in shell):
    path_to_shell = f"{home}/.zshrc"
elif ("bash" in shell):
    path_to_shell = f"{home}/.bashrc"
else:
    sys.exit(
        f" Automatic installation only works for BASH/ZSH, {shell} is not supported.")

# Try to append microscripts to PATH.
with open(path_to_shell, "r") as zshrc:
    original_lines = zshrc.readlines()

with open(path_to_shell, "a+") as zshrc:
    if (original_lines):
        for line in original_lines:
            stripped_line = line.rstrip()
            if ("PATH" in stripped_line):
                if ("microscripts" in stripped_line):
                    sys.exit("Looks like microscripts is already in your PATH.")
                stripped_line += f":{microscripts}"
                zshrc.write(stripped_line)
    else:
        zshrc.write(f"PATH=$PATH:{microscripts}")
        print(
            f"Looks like you didn't have a PATH set, created one and added it to {path_to_shell} for you.")
