export PATH=~/.dotnet/tools/:$PATH
export BROWSER=none
export EDITOR=vim

alias nuget="mono /usr/local/bin/nuget.exe"
alias ls="ls -l"
alias lsa="ls -la"

case "$(uname -s)" in
    Darwin*)    alias lsblk="diskutil list";;
esac
