export PATH=~/.dotnet/tools/:~/.composer/vendor/bin:/Applications/MAMP/Library/bin:$PATH

# Variables
export EDITOR=vim

# VIM
alias vim="nvim"

#.NET
alias nuget="mono /usr/local/bin/nuget.exe"

# Git
alias gb="git branch --show-current"
alias grs="git remote show"
alias ga="git add"
alias gs="git status"
alias gm="git commit -m"
alias gp="git push" 

# Node/NPM
alias nr="npm run"

# Go
alias gr="go run *.go"

# Docker
alias d='docker'
alias dc='docker container'
alias di='docker image'
alias prune='docker system prune'

# Misc
alias ll='ls -l'
alias weather="osascript -e 'display notification \"Salt Lake City (KMTX)\" with title \"Fetching Radar\"'; mpv --loop-file=inf \"https://radar.weather.gov/ridge/lite/KMTX_loop.gif\""

case "$(uname -s)" in
    Darwin*)    alias lsblk="diskutil list";;
esac
