require('core.plugconf.colors')
require('core.plugconf.completions')
require('core.plugconf.lsp')
require('core.plugconf.lualine')
require('core.plugconf.nvim-tree')
require('core.plugconf.telescope')
require('core.plugconf.treesitter')
