export PATH=~/.bin:/.dotnet/tools/:~/.composer/vendor/bin:/Applications/MAMP/Library/bin:~/.npm-global/bin:/usr/local/share/dotnet/x64:~/.go/bin:$PATH

function macdisk() {
	if ! command -v smartctl &> /dev/null
	then
		echo "smartctl is not in path, maybe try <brew install smartmontools>"
		return
	fi
	smartctl --all /dev/disk0
}

# OS-specific aliases
case "$(uname -s)" in
    Darwin*)
	alias lsblk="diskutil list"
	alias disk="macdisk"
	;;
esac

alias ll='ls -l'
alias weather="osascript -e 'display notification \"National Weather Service\" with title \"Fetching Radar\"'; mpv --loop-file=inf \"https://radar.weather.gov/ridge/lite/KMTX_loop.gif\""

# Variables
export EDITOR=nvim

#.NET
alias nuget="mono /usr/local/bin/nuget.exe"

# Git
alias g="git"
alias gb="git branch --show-current"
alias grs="git remote show"
alias ga="git add"
alias gs="git status"
alias gm="git commit -m"
alias gp="git push"

# Node/NPM
alias nr="npm run"

# React
alias rd="react-devtools"

# Go
export GOPATH=~/.go
alias gr="go run *.go"

# Docker
alias dc='docker container'
alias di='docker image'
alias dp='docker rmi -f $(docker images -a -q)'
alias dprune='docker system prune'

# Python
alias serve='python3 -m http.server'